# Generated by Django 3.0.3 on 2020-02-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_eng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='group_rasp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=30)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('tue', 'tuesday'), ('WED', 'Wednesday'), ('THI', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=3)),
                ('lesson', models.CharField(choices=[('MON', 'Monday'), ('tue', 'tuesday'), ('WED', 'Wednesday'), ('THI', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
