# Generated by Django 3.0.3 on 2020-02-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_eng', '0002_auto_20200229_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_rasp',
            name='auditories',
            field=models.CharField(default='unknow', max_length=10),
        ),
        migrations.AddField(
            model_name='group_rasp',
            name='subject',
            field=models.CharField(default='unknow', max_length=100),
        ),
        migrations.AddField(
            model_name='group_rasp',
            name='teacher',
            field=models.CharField(default='unknow', max_length=100),
        ),
        migrations.AlterField(
            model_name='group_rasp',
            name='lesson',
            field=models.CharField(choices=[('FIR', 'first lesson'), ('SEC', 'second lesson'), ('THI', 'thied lesson'), ('FOU', 'fourth lesson'), ('FIF', 'fifth lesson'), ('SIX', 'sixth lesson'), ('SEV', 'seventh lesson')], default='FIR', max_length=3),
        ),
    ]
